CREATE TABLE #t(id int IDENTITY(1, 1) 
PRIMARY KEY NOT NULL, amount INT NULL)

INSERT INTO #t
SELECT 10 UNION ALL
SELECT 20 UNION ALL
SELECT 30 UNION ALL
SELECT 40 
 
SELECT t1.Amount,
(
	SELECT SUM(t2.Amount) 
	FROM #t AS t2 
	WHERE t2.id <= t1.id 
) AS Total
FROM #t AS t1

DROP TABLE #t