CREATE TABLE #t(id int IDENTITY(1, 1) 
PRIMARY KEY NOT NULL, text CHAR(10) NULL)

INSERT INTO #t
SELECT 'abc' UNION ALL
SELECT 'def' UNION ALL
SELECT 'ghi' UNION ALL
SELECT 'def' UNION ALL
SELECT 'ghi' UNION ALL
SELECT 'jkl' UNION ALL
SELECT 'mno'
 
SELECT * FROM #t

SELECT ROW_NUMBER() OVER(PARTITION BY text 
ORDER BY text) AS 'Row Number', text 
FROM #t

DROP TABLE #t